#pragma once
// Warning: This file has been autogenerated by the tool!
#include <glm/glm.hpp>
#include <glad/glad.h>
#include "types.h"
#include "buffers.h"
struct Example_Program
{
    GLuint id;
    inline void use()
    {
        glUseProgram(id);
    }
    GLint bar_location;
    GLint baz_location;
    GLint foo_location;
    GLint thing_test_location;
    GLint thing_foo_location;
    GLint thing_bar_location;
    GLint Stuff_block_index;
    GLint Stuff_2_block_index;
    inline void bar(glm::float32 bar)
    {
        glUniform1f(bar_location, bar);
    }
    inline void baz(glm::mat4 baz)
    {
        glUniformMatrix4fv(baz_location, 1, GL_FALSE, (float*)&baz);
    }
    inline void foo(glm::vec3 foo)
    {
        glUniform3fv(foo_location, 1, (float*)&foo);
    }
    inline void thing(Thing thing)
    {
        glUniform3fv(thing_test_location, 1, (float*)&thing.test);
        glUniform2fv(thing_foo_location, 1, (float*)&thing.foo);
        glUniformMatrix4fv(thing_bar_location, 1, GL_FALSE, (float*)&thing.bar);
    }
    inline void Stuff_block(Stuff_Block Stuff_block)
    {
        glUniformBlockBinding(id, Stuff_block_index, Stuff_block.binding_point);
    }
    inline void Stuff_2_block(Stuff_2_Block Stuff_2_block)
    {
        glUniformBlockBinding(id, Stuff_2_block_index, Stuff_2_block.binding_point);
    }
    inline void query_locations()
    {
        bar_location = glGetUniformLocation(id, "bar");
        baz_location = glGetUniformLocation(id, "baz");
        foo_location = glGetUniformLocation(id, "foo");
        thing_test_location = glGetUniformLocation(id, "thing.test");
        thing_foo_location = glGetUniformLocation(id, "thing.foo");
        thing_bar_location = glGetUniformLocation(id, "thing.bar");
        Stuff_block_index = glGetUniformBlockIndex(id, "Stuff");
        Stuff_2_block_index = glGetUniformBlockIndex(id, "Stuff_2");
    }
    inline void uniforms(glm::float32 bar_v, glm::mat4 baz_v, glm::vec3 foo_v, Thing thing_v)
    {
        bar(bar_v);
        baz(baz_v);
        foo(foo_v);
        thing(thing_v);
    }
};
